### ISSUE TITLE
Removal of default null is incompatible

### ISSUE THREAD

**Issue by kelunik** [joshdifabio/semantic-diff#2]
https://github.com/joshdifabio/semantic-diff/blob/master/tests/Diff/FactoryTest.php#L141-L159

That one should be `INCOMPATIBLE_API`, since `null` is no longer an allowed value.

**Comment by joshdifabio** [comment]
I might have misunderstood, but the following [will allow `null`](https://3v4l.org/Ae3sO).

``` php
public function helloWorld($foobar = 1) {}
```

**Comment by kelunik** [comment]
Oh, you're right, it does as long as there are no type declarations, missed that.
